### ISSUE TITLE
Huge slowdown with multiple card loading

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#103]
It seems the engine is not caching tsv data efficiently, loading/reading full file each time cards are loaded (for each load cards function call). According to some simple tests I made this can be even 2/3 of scenario setup time with the approach taken in my Arkham mod. And this will only grow worse as the tsv will double or triple in size. At minimum the contents should be cached/read more efficiently inside a single request process, optimally even between requests (after all - all instances of the game should use the same data per version of the mod/tsv).

**Comment by seastan** [comment]
I now cache the tsv, with a 10 second expiry time. You should see greatly improved loading times.
