### ISSUE TITLE
Card image not loading for quest

### ISSUE THREAD

**Issue by DeathStapler** [seastan/DragnCards#15]
When loading the quest The Thing in the Depths, a card in the Set Aside pile doesn't load.  I see in the dev tools that it is repeatedly trying to load it.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/1326302/145115938-bcea971f-ea2c-4ff6-aece-bf1a0127b108.png">

**Comment by seastan** [comment]
Fixed.
