### ISSUE TITLE
Errata Cards

### ISSUE THREAD

**Issue by Jangoria** [seastan/DragnCards#4]
**Low Priority**

Horn of Gondor and Boromir on Dragncards are showing the pre-errata images. 

My assumption is this applies to most/all cards that have been erratad.
I also assume that the "cards" on Dragncards use image urls for their artwork.

**Proposed Solution**

Update image urls/paths for Errata cards. Possible with a new toggle under options which allows users to use the errata version or the originally printed version.

A google doc of the 29 errata cards for reference: https://docs.google.com/spreadsheets/d/1aTGqFWoLR2cZfT8hggZWUBRCs3uUJv9jiJrruhD-3pQ/edit#gid=125392851
The original post containing this: https://www.reddit.com/r/lotrlcg/comments/gkypki/complete_player_card_prepost_errata_compendium/

**Comment by OleksandrBerchenko** [comment]
I believe DragnCards inherited all PRE-errata images from OCTGN.  See https://github.com/seastan/Lord-of-the-Rings/issues/18:

-     Horn of Gondor
-     Wandering Took
-     Will of the West
-     The Necromancer's Tower
-     A Burning Brand
-     Boromir
-     Out of the Wild
-     Legacy of Durin
-     Hama
-     Erebor Battle Master
-     Love of Tales,
-     We Are Not Idle
-     A Elbereth! Gilthoniel!
-     Thror's Map
-     A Watchful Peace
-     The Power of Mordor
-     Trained for War
-     Counter-attack
-     Caldara
-     Impenetrable Fog
-     Secret Entrance
-     Blue Mountain Trader
-     Wingfoot
-     Devilry of Saruman
-     The Passage of the Marshes
-     Helm of Secrecy

**Comment by seastan** [comment]
Fixed.
