### ISSUE TITLE
Menu on tablet bug

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#54]
It's very hard to get the card menu to show on tablets with touch mode enabled.

First tap shows large card image. Long tap means dragging, so there's no reliable way to get the menu shown. I suggest the following options to solve it:
a) either show the menu on first tap along large card image
b) or show the menu on second tap of the same card (if large image is already visible)
c) or show the menu when lower half of card is tapped, and large image when upper half of card is tapped

Personally I like a) most, followed by b).

**Comment by morvael** [comment]
This is a blocker.

**Comment by seastan** [comment]
Implemented (a)
