### ISSUE TITLE
Scrollbar at the bottom of the screen bug

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#56]
Chrome on iPad, fullscreen app, touch mode enabled. Bottom-center there's a scrollbar knob visible, slightly covering the bottom row of buttons.

**Comment by seastan** [comment]
Not able to reproduce on my Android tablet

**Comment by morvael** [comment]
Looks like that:
![IMG20240825230911](https://github.com/user-attachments/assets/4a51433d-c87a-4c36-b731-3ff15cda3ec2)

**Comment by morvael** [comment]
Lol, it looks it's a feature of iOS. I get the same bar in other apps. Sorry for confusion. Looks like a scrollbar.

**Comment by morvael** [comment]
Looks like it's a feature that isn't easy to turn off, so it seems should be taken into account when planning GUI (don't put anything there). Sadly it goes over the expand log button.

**Comment by seastan** [comment]
How annoying
