### ISSUE TITLE
Portrait card behind landscape card bug

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#58]
When "contracted" the card looks natural:
![image](https://github.com/user-attachments/assets/144aaa4a-621d-4bbc-a028-54302e8a63a9)
When "expanded" it looks unnatural:
![image](https://github.com/user-attachments/assets/28567c26-ea00-4940-ad5f-e13ecd95cf5d)

IMHO in such situation cards should be always aligned to top left corner, and never move during expansion of the list (only 2nd and further cards should move down to allow seeing them).

**Comment by seastan** [comment]
I like the way this looks right now

**Comment by morvael** [comment]
What's worse is that the card is missing large part of it's top when contracted. Maybe that different height is what makes it so unnatural.

**Comment by morvael** [comment]
Ah, it's cut off only because the group region is small - so somehow layout doesn't make sure to move the main card down enough (or at all).

**Comment by morvael** [comment]
![image](https://github.com/user-attachments/assets/35ce5244-4711-4e32-8dff-d85e1c12ebad)

![image](https://github.com/user-attachments/assets/c717f57d-9d38-44f8-8f9d-bd864a1694f4)
