### ISSUE TITLE
Multiple cards behind bug

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#59]
It seems, that unlike in functionality presentation video, when more than 1 card is attached behind a card, and the cards are expanded only one card is shown and the rest not at all (they should each have a part of them made visible):
![image](https://github.com/user-attachments/assets/15527ffc-c2c2-4371-a1eb-2b353d41c5d7)

**Comment by morvael** [comment]
This is a blocker.

**Comment by seastan** [comment]
What type of region is this in?

**Comment by morvael** [comment]
I can confirm this for at least free and fan and row.

**Comment by seastan** [comment]
Not able to replicate. How do I attach cards in the free region of your plugin? Seems you've disabled most combinations.

**Comment by morvael** [comment]
Wow, it seems to be working now. Was something changed?
![image](https://github.com/user-attachments/assets/7a82292d-728e-452d-beaf-25790d70cb31)
Only #58 remains, but it's just cosmetics.

**Comment by seastan** [comment]
Fixed by some commit a couple weeks ago, I forget which.
