### ISSUE TITLE
All games removed from lobby 9:30 PM ET 7/16/2021

### ISSUE THREAD

**Issue by verrilli** [seastan/DragnCards#6]
My game started acting flaky - hot keys said they did something but it was not reflected on the board.
Tried to save game and it said saved.
Then I went back to lobby and all games were gone.
Tried to load game from profile and it was not there.
9:30pm Eastern US Time

**Comment by seastan** [comment]
I have upgraded the server so hopefully it doesn't happen again

**Comment by verrilli** [comment]
Thanks!
