### ISSUE TITLE
SORT_LIST function

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#61]
Would be great to have a function `["SORT_LIST", "$LIST", "prop", "ASC"]` which could sort any list of objects (usually cards) using their property `prop` with given sort order.

**Comment by morvael** [comment]
The function should return the sorted list (not change the original), so it could be saved using `VAR` or `UPDATE_VAR` etc.

**Comment by seastan** [comment]
Added SORT_OBJ_LIST
