### ISSUE TITLE
FOR_EACH_KEY_VAL sort bug

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#73]
It's impossible to provide sortProp and sortOrder to FOR_EACH_KEY_VAL function. Results in the following error:
```
%FunctionClauseError{args: nil, arity: 2, clauses: nil, function: :get_in, kind: nil, module: Kernel}
```

**Comment by seastan** [comment]
We have SORT_OBJ_LIST now so I'm going to deprecate this rather than fix it

**Comment by morvael** [comment]
:+1:

**Comment by morvael** [comment]
So just remove from documentation.
