### ISSUE TITLE
Do not listen to F11 hotkey

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#76]
F11 is often reserved for full screen mode. In case of Dragncards I have to use menu to enter fullscreen mode in browser as otherwise the game "eats" keypress. Luckly in full screen mode F11 works as designed, browser has priority and exits full screen mode.

**Comment by morvael** [comment]
I wouldn't also let the engine or the plugin block hard refresh option 
https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

**Comment by morvael** [comment]
For full screen it seems it's mostly F11 on Windows and Linux, and Ctrl Cmd F on Mac.

**Comment by seastan** [comment]
Fixed
