### ISSUE TITLE
Missing Deck

### ISSUE THREAD

**Issue by ValarMorghulisV** [seastan/DragnCards#8]
I completed my first game on DragnCards and clicked Reset Game -> Mark as Victory.  After this my deck disappeared and I can't locate it.  I am also unable to re-load my deck using the OCTGN file I originally loaded it with.  To get around the issue I was able to unload my deck and then re-load the deck.

I did load a different quest after resetting the game, but my deck was missing before that.

**Comment by seastan** [comment]
Inability to reload OCTGN decks has been resolved
