### ISSUE TITLE
Different way of reading modifier keys (shift, ctrl, alt)

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#84]
Currently it's impossible to use a hotkey defined as `{` - as it requires pressing shift on standard keyboard, and the game thinks it's `Shift+{` hotkey (in reality it's either `Shift+[` or `{` but not `Shift+{`). I think the game should distinguish between shift used with letters and shift used with something else which in most cases should be treated as different character without shift. What about getting rid of Shift all together and just making distinction between upper and lower case letters?

Also, keeping modifier keys status as boolean flags is unreliable and they often remain "pressed" according to the game. It would be great if the engine would use standard modifier flags from key and mouse events like this one: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey

**Comment by seastan** [comment]
I'll take a look at the modifier flags. But I don't think I want to allow people to define separate hotkeys for "A" and "a". I think that will lead to confusion. I think there's a reason no game does that.

**Comment by morvael** [comment]
`A` is simply `Shift+a` :)

As I said, you can show `a` as `A` and `A` as `Shift+A`, but please do this only for letters, not symbols. So `{` not `Shift+[` or even worse, `Shift+{`.

**Comment by morvael** [comment]
I confirm it looks to be working ok now. Symbols are reported without shift.
