### ISSUE TITLE
Support comments in JSONs

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#86]
The import GUI and API could perhaps put the imported files through a "cleaner" that could handle comments in JSON (I know, not standard feature, but for example Jackson library parsers can have such features enabled). That way it would be possible to write commented code in a more natural way
```
//this does something
["DO_SOMETHING"]
```
and still offer clean json to the engine.

**Comment by morvael** [comment]
Some ideas for parser options: https://github.com/FasterXML/jackson-core/wiki/JsonParser-Features

**Comment by seastan** [comment]
Added
