### ISSUE TITLE
Popup and menus

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#87]
I think previously popup menus were hidden under normal menus. Now it's the opposite. Menu is unusable while popup is on. I think popups should be moveable, that would allow the player to uncover menu and/or cards beneath the popup in default position, if need be.

**Comment by morvael** [comment]
Popups move (is it new stuff?) but tapping popup menu items no longer works on tablet.

**Comment by seastan** [comment]
I looks like making the prompts draggable has broken them for tablets

**Comment by morvael** [comment]
Yes, that's sad :)

**Comment by seastan** [comment]
Add a drag handle to prompts, should work now hopefully.
