### ISSUE TITLE
Ability to drag a card to/from sideboard

### ISSUE THREAD

**Issue by morvael** [seastan/dragncards#99]
...in other words allow to execute a hotkey that shows/hides some regions while the card is being dragged, and allow dropping it in such regions that were shown/revealed by hiding others during its drag.

Currently the card "doesn't see" the regions change and what's worse doesn't drop at all on mouse release but hangs "in the air" until page reload.

**Comment by seastan** [comment]
Not possible with the the drag and drop library I'm using.
